# Generated by Django 4.2.7 on 2023-11-18 08:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patient', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='phone',
            field=models.CharField(max_length=40),
        ),
        migrations.AlterField(
            model_name='patient',
            name='postal_code',
            field=models.IntegerField(),
        ),
    ]
