# Generated by Django 4.2.7 on 2023-11-18 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinic', '0002_medicalstaff'),
    ]

    operations = [
        migrations.AddField(
            model_name='medicalstaff',
            name='position',
            field=models.CharField(choices=[('doctor', 'Doctor'), ('nurse', 'Nurse'), ('director', 'Director')], default='doctor', max_length=20),
            preserve_default=False,
        ),
    ]
