# Generated by Django 4.2.7 on 2023-11-21 20:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinic', '0002_remove_appointment_datetime_appointment_date_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='medication',
            name='instructions',
        ),
        migrations.AddField(
            model_name='medication',
            name='dosage',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='medication',
            name='frequency',
            field=models.CharField(default='daily', max_length=100),
            preserve_default=False,
        ),
    ]
