# Generated by Django 4.2.7 on 2023-11-21 20:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clinic', '0003_remove_medication_instructions_medication_dosage_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='medication',
            name='datetime',
        ),
    ]
