# Generated by Django 4.2.7 on 2023-11-19 08:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clinic', '0004_remove_medicalstaff_province_medicalstaff_department_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='patient',
            name='province',
        ),
    ]
