# Generated by Django 4.2.7 on 2023-11-19 10:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('clinic', '0006_doctor_delete_medicalstaff'),
    ]

    operations = [
        migrations.CreateModel(
            name='Consultation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('symptoms', models.CharField(max_length=40)),
                ('illness', models.CharField(max_length=255)),
                ('notes', models.CharField(max_length=255)),
                ('patient_type', models.CharField(choices=[('in', 'In Patient'), ('out', 'Out Patient')])),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='clinic.doctor')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='clinic.patient')),
            ],
        ),
    ]
