# Generated by Django 4.2.7 on 2023-11-19 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinic', '0008_alter_consultation_patient_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='consultation',
            name='datetime',
            field=models.DateTimeField(default='2023-11-19'),
            preserve_default=False,
        ),
    ]
