# Generated by Django 4.2.7 on 2023-11-19 16:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('clinic', '0009_consultation_datetime'),
    ]

    operations = [
        migrations.CreateModel(
            name='Medication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('instructions', models.CharField(max_length=255)),
                ('duration', models.CharField(max_length=50)),
                ('datetime', models.DateTimeField()),
                ('consultation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clinic.consultation')),
            ],
        ),
    ]
