# Generated by Django 4.2.7 on 2023-11-19 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinic', '0010_medication'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='medication',
            name='duration',
        ),
        migrations.AddField(
            model_name='medication',
            name='end',
            field=models.DateField(default='2023-11-19'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='medication',
            name='start',
            field=models.DateField(default='2023-11-19'),
            preserve_default=False,
        ),
    ]
