# Generated by Django 4.2.7 on 2023-11-19 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinic', '0011_remove_medication_duration_medication_end_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='allergies',
            field=models.CharField(default='', max_length=255),
            preserve_default=False,
        ),
    ]
